version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
      time: '07:00'
      timezone: Europe/Berlin
    assignees:
      - ffried
    reviewers:
      - ffried

  - package-ecosystem: nuget
    directory: /server
    schedule:
      interval: daily
      time: '07:00'
      timezone: Europe/Berlin
    assignees:
      - ffried
    reviewers:
      - ffried
    groups:
      entity-framework-core:
        patterns:
          - 'Microsoft.EntityFrameworkCore'
          - 'Microsoft.EntityFrameworkCore.*'
      aspnet-core:
        patterns:
          - 'Microsoft.AspNetCore'
          - 'Microsoft.AspNetCore.*'

  - package-ecosystem: nuget
    directory: /raspi
    schedule:
      interval: daily
      time: '07:00'
      timezone: Europe/Berlin
    assignees:
      - ffried
    reviewers:
      - ffried

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      time: '07:00'
      timezone: Europe/Berlin
    assignees:
      - ffried
    reviewers:
      - ffried
