// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SensorServer;

#nullable disable

namespace SensorServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class MeasurementsRepositoryModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("SensorServer.Models.Measurement", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("HumidityPercent")
                        .HasColumnType("REAL");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double?>("PressureHectopascals")
                        .HasColumnType("REAL");

                    b.Property<double>("TemperatureCelsius")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("HumidityPercent");

                    b.HasIndex("Location");

                    b.HasIndex("PressureHectopascals");

                    b.HasIndex("TemperatureCelsius");

                    b.ToTable("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
