name: Validate Dependencies

on:
  pull_request:
    branches: [ main ]
    paths: [ 'server/**/*.csproj' ]

jobs:
  validate-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/server/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('server/**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - working-directory: server
        run: dotnet restore
