name: Validate Dependencies

on:
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: read
  contents: read

jobs:
  check-files:
    runs-on: ubuntu-latest
    outputs:
      has-relevant-changes: ${{ steps.changes.outputs.changes != '[]' }}
    permissions:
      pull-requests: read
    steps:
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            workflow:
              - '.github/workflows/validate-dependencies.yml'
            csprojects:
              - '*.csproj'
              - '**/*.csproj'

  validate-dependencies:
    needs: check-files
    if: ${{ needs.check-files.outputs.has-relevant-changes == 'true' }}
    runs-on: ubuntu-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
          cache: true
          cache-dependency-path: '*/*.csproj'
      - working-directory: server
        run: dotnet restore

  validate-dependencies-result:
    runs-on: ubuntu-latest
    needs:
      - check-files
      - validate-dependencies
    if: ${{ always() }}
    permissions: {}
    steps:
      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        env:
          DEPENDENCIES: ${{ toJson(needs) }}
        run: |
          FAILED_JOBS="$(echo "${DEPENDENCIES}" | jq --raw-output '
            to_entries[]
            | select(.value.result == "failure" or .value.result == "cancelled")
            | .key')"
          echo "::error title=Failed Jobs::The following jobs failed:\n${FAILED_JOBS}"
          exit 1
