name: Validate Dependencies

on:
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: read
  contents: read

jobs:
  check-files:
    runs-on: ubuntu-latest
    outputs:
      has-relevant-changes: ${{ steps.changes.outputs.csprojects }}
    permissions:
      pull-requests: read
    steps:
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            csprojects:
              - '*.csproj'
              - '**/*.csproj'

  validate-dependencies:
    needs: check-files
    if: ${{ needs.check-files.outputs.has-relevant-changes == 'true' }}
    runs-on: ubuntu-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
          cache: true
          cache-dependency-path: '*/*.csproj'
      - working-directory: server
        run: dotnet restore
